### PR TITLE
Upgrade to .NET8

### PR DESCRIPTION
**Pull request by josephmyers**

### CODE REVIEW

**Comment by megahirt** [comment]
Hi @hatton !

@josephmyers and I did an experiment on the smallest .Net Framework project I could think of (sheetswiper) to upgrade it to .Net 8 Windows Forms.  I wanted to check with you first about me merging PRs in this repo and making some changes, including possibly releasing a new sheetswiper.  Are you ok with that?

This is mostly an experiment to evaluate the effort and impact of upgrading a project to .Net 8 Windows forms.

**Comment by megahirt** [comment]
@josephmyers Ideally future PRs should start on a feature branch and not master, even on your own fork.  I don't think this can be changed without starting a new PR - but that's not necessary this time around.

**Review by megahirt — APPROVED** [review]
LGTM thanks Joseph!

Love the new streamlined csproj.

**Comment by hatton** [comment]
> Are you ok with that?

Yes

**Pull request merged**
